name: Deploy

on:
  push:
    tags:
      - '*'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 'Notify: preparing'
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          format: markdown
          args: |
            🆕 *kremen/transport-web:* preparing for the new build
      - uses: actions/checkout@v1
      - run: yarn install
      - name: Preparing .env file
        run: 'echo "MAPS_API_KEY_PROD=$MAPS_API_KEY_PROD" > .env'
        env:
          MAPS_API_KEY_PROD: ${{secrets.MAPS_API_KEY_PROD}}
      - name: 'Notify: build started'
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          format: markdown
          args: |
            🔥 *kremen/transport-web:* build started
      - run: yarn dist:prod
      - name: 'Notify: build finished'
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          format: markdown
          args: |
            🔥 *kremen/transport-web:* build finished
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
      - name: 'Notify: finished'
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          format: markdown
          args: |
            🏁 *kremen/transport-web:* new version deployed successfully
  
